class IO_Error(Exception):
    pass
